version: '3'

services:
  keycloak:
    build:
      context: .docker-keycloak/
      dockerfile: Dockerfile
    networks:
      - progs-apps-network
    ports:
      - 8080:8080
    command:
      - start-dev

  spring-boot:
    build:
      context: .docker-spring-boot/
      dockerfile: Dockerfile
    networks:
      - progs-apps-network
    ports:
      - 8081:8081
    depends_on:
      - "keycloak"

networks:
  progs-apps-network:
    driver: bridge